SHOP_POWER_UPS = [
    {
        "name": "Meditate",
        "description": "+1.5 Sec Time",
        "cost": 15,
        "effect_key": "TIME_BOOST",
        "effect_value": 1.5,
        "is_active": False,
        "rect": None,
        "color": (100, 180, 255),
    },
    {
        "name": "Hire nerd kids",
        "description": "Remove 2 Wrong",
        "cost": 40,
        "effect_key": "CLUE_MASTER",
        "effect_value": 1,
        "is_active": True,
        "rect": None,
        "color": (180, 100, 255),
    },
    {
        "name": "Go to gym",
        "description": "Attack + 1",
        "cost": 30,
        "effect_key": "DMG_MULTIPLIER",
        "effect_value": 1,
        "is_active": False,
        "rect": None,
        "color": (255, 100, 100),
    },
    {
        "name": "Eat Mama",
        "description": "+1 Extra Life",
        "cost": 50,
        "effect_key": "LIFE_SAVER",
        "effect_value": 1,
        "is_active": False,
        "rect": None,
        "color": (218, 165, 32),
    },
    {
        "name": "Drink redbull",
        "description": "+1 Max HP",
        "cost": 10,
        "effect_key": "MAX_HP_BOOST",
        "effect_value": 1,
        "is_active": False,
        "rect": None,
        "color": (34, 139, 34),
    },
]
